# Use uma imagem base Python
FROM python:3.11-slim

# Definir o diretório de trabalho
WORKDIR /app

# Copiar o arquivo de requisitos e instalar as dependências
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiar o restante do código da aplicação
COPY ./servidor /app

# Comando para rodar a aplicação
# O NOME_SERVIDOR e a lista de SERVIDORES_JOGO serão definidos no docker-compose.yml
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
