# Use uma imagem base Python
FROM python:3.11-slim

# Definir o diretório de trabalho
WORKDIR /app

# Copiar o arquivo de requisitos e instalar as dependências
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiar o código do cliente
COPY ./cliente /app

# Comando de entrada
CMD ["python", "cliente_cmd.py"]
